lr:
  type: categorical
  value: [1e-4, 5e-4, 1e-3, 5e-3]

dropout:
  type: float
  step: 0.1
  value: [0.0, 0.6]
  round: 1

emb_dropout:
  type: float
  step: 0.1
  value: [0.0, 0.6]
  round: 1

alpha:
  type: float
  step: 0.1
  value: [0.3, 0.7]
  round: 1
