lr:
  type: categorical
  value: [1e-4, 5e-4, 1e-3, 5e-3]

decay:
  type: categorical
  value: [0.0, 1e-4, 1e-3, 1e-2]

factor_num:
  type: categorical
  value: [8, 16, 32, 64]

num_layers:
  type: categorical
  value: [1, 2, 3, 4, 5]

dropout:
  type: float
  step: 0.1
  value: [0.0, 0.8]
  round: 1

emb_dropout:
  type: float
  step: 0.1
  value: [0.0, 0.8]
  round: 1

use_layer_norm:
  type: categorical
  value: [true, false]
