lr:
  type: categorical
  value: [1e-4, 5e-4, 1e-3, 5e-3]

decay:
  type: categorical
  value: [0.0, 1e-4, 1e-3, 1e-2]

emb_dropout:
  type: float
  step: 0.1
  value: [0.0, 0.8]
  round: 1

dropout:
  type: float
  step: 0.1
  value: [0.0, 0.8]
  round: 1

train_batch_size:
  type: categorical
  value: [32, 64, 128, 256]

factor_num:
  type: categorical
  value: [8, 16, 32, 64]

deep_net_num_layers:
  type: int
  value: [1, 4]

cross_net_num_layers:
  type: int
  value: [1, 6]
