lr:
  type: categorical
  value: [1e-4, 5e-4, 1e-3, 5e-3]

factor_num:
  type: categorical
  value: [8, 16, 32, 64]

num_layers:
  type: categorical
  value: [2, 3, 4]

dropout:
  type: float
  step: 0.1
  value: [0.0, 0.6]

emb_dropout:
  type: float
  step: 0.1
  value: [0.0, 0.6]

alpha:
  type: float
  step: 0.1
  value: [0.3, 0.7]
